// <auto-generated />
using System;
using GreenGenius.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenGenius.Common.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenGenius.Common.Data.Entities.Garden", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name");

                    b.ToTable("gardens", (string)null);
                });

            modelBuilder.Entity("GreenGenius.Common.Data.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BinomialName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("DaysToMaturity")
                        .HasColumnType("integer");

                    b.Property<string>("DescriptionFr")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Key")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LifeCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("TemperatureMinC")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("GreenGenius.Common.Data.Entities.PlantNeeds", b =>
                {
                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.Property<int>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<string>("RootDepth")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("SoilPhMax")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<decimal?>("SoilPhMin")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<int>("SpacingPlantCm")
                        .HasColumnType("integer");

                    b.Property<int>("SpacingRowCm")
                        .HasColumnType("integer");

                    b.Property<int>("SpreadCm")
                        .HasColumnType("integer");

                    b.Property<string>("Sunlight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WaterNeed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PlantId");

                    b.ToTable("plant_needs", (string)null);
                });

            modelBuilder.Entity("GreenGenius.Common.Data.Entities.PlantTraits", b =>
                {
                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DroughtTolerant")
                        .HasColumnType("boolean");

                    b.Property<bool>("DynamicAccumulator")
                        .HasColumnType("boolean");

                    b.Property<bool>("NitrogenFixer")
                        .HasColumnType("boolean");

                    b.Property<bool>("PollinatorFriendly")
                        .HasColumnType("boolean");

                    b.HasKey("PlantId");

                    b.ToTable("plant_traits", (string)null);
                });

            modelBuilder.Entity("GreenGenius.Common.Data.Entities.PlantNeeds", b =>
                {
                    b.HasOne("GreenGenius.Common.Data.Entities.Plant", "Plant")
                        .WithOne("Needs")
                        .HasForeignKey("GreenGenius.Common.Data.Entities.PlantNeeds", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenGenius.Common.Data.Entities.PlantTraits", b =>
                {
                    b.HasOne("GreenGenius.Common.Data.Entities.Plant", "Plant")
                        .WithOne("Traits")
                        .HasForeignKey("GreenGenius.Common.Data.Entities.PlantTraits", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenGenius.Common.Data.Entities.Plant", b =>
                {
                    b.Navigation("Needs")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
