<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\GreenGenius.Common.Data\GreenGenius.Common.Data.csproj" />
      <ProjectReference Include="..\GreenGenius.Infra.Hosting\GreenGenius.Infra.Hosting.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
</Project>
