name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0 # Required for new code

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup .NET
        uses: actions/setup-dotnet@v6.0.0
        with:
          dotnet-version: '10.0.x'

      - name: Dotnet tools
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global dotnet-coverage

      - name: Build, tests and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
        run: |
          dotnet-sonarscanner begin \
            /k:"mgendre_green-genius" \
            /o:"mgendre" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${SONAR_TOKEN}" \
            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml

          dotnet restore
          dotnet build --no-restore --no-incremental
          dotnet-coverage collect "dotnet test --no-build" -f xml -o coverage.xml

          dotnet-sonarscanner end /d:sonar.token="${SONAR_TOKEN}"
